# Generated by Django 5.0.6 on 2024-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThoughtShare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='context',
        ),
    ]
